### ISSUE TITLE
 #error Invalid Parameters: Use LCD_PRINT or DEBUG_PRINT 

### ISSUE THREAD

**Issue by MailMalone** [kr4fty/Ardutester#1]
i am getting this problem when compiling.
please try to make a lcdi2c version.

**Comment by kr4fty** [comment]
Hi, you must choose between lcd mode or debug mode. For this you must comment one of the two lines where they are defined:

```
67  #define LCD_PRINT 
...
70  //#define DEBUG_PRINT 
```

or

```
67  //#define LCD_PRINT 
...
70  #define DEBUG_PRINT 
```
